# Generated by Django 5.0.4 on 2024-05-07 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.video'),
        ),
    ]
